# --------------
# -- Settings --
# --------------
# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://powerhouseclans.github.io/powerhouseweb/"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "PowerhouseClans"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Powerhouse Clans | Clash of Clans"
  description: "This is the Powerhouse Clans official website."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "Powerhouse"
  description: "This is the Powerhouse Clans official website."
  date:        "Fall 2017"
  location:    "United States"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://powerhouseclans.github.io/powerhouseweb/success.html"
      - text: "Sponsor"
        href: "mailto:powerhouseclans@gmail.com"

  about:
    description: >
      Powerhouse Clans are a group of allied clans with the powerhouse name. Much like a franchise, powerhousesis1 is the base 
      of operations for all powerhouse clans and every powerhouse clan leader originated from powerhousesis1. An elite group 
      of clans, anyone within the powerhousesis1 clan is elegible to become a franchise.

  # Info Sections
  info:
    sections:
      - image: "images/programmingicon.jpg"
        href: "www.github.com"
        title: "Apply."
        description: >
          Learn various programming languages including Java, HTML, CSS, Python, C++, Javascript, and more at your own pace.
      - image: "images/githubicon.png"
        href: "www.github.com"
        title: "Contribute."
        description: >
          Utilize github to collaborate on projects and host websites for free!
      - image: "images/socialmedia.jpg"
        href: "www.github.com"
        title: "Establish."
        description: >
          Connect your project with the world through social media and your very own github pages website.

  # Frequently asked questions.
  faq:
    - question: "What is Clash of Clans"
      answer: >
        Clash of Clans is a multiplayer smartphone game in which players build a base that is ever expanding.
        Players can attack other players bases, join or create clans, and participate in huge clan battles.
    - question: "How much does it cost?"
      answer: >
        Playing the game is free. Only gems(not needed) may be purchased for a boost.
    - question: "Why should I join a Powerhouse Clan?"
      answer: >
        The Powerhouse name lends credibility. It is a privilege. Everyone in powerhouse clans have been sorted and
        always contribute to the clans.
    - question: "Where are the clans located?"
      answer: >
        Powerhouse Clans location is based on where the leaders are located.
    - question: "What are the requirments to join?"
      answer: >
        You must be over level 100 to join any powerhouse clan unless you were grandfathered into a clan. 
        You must have at least 2400 trophies to join, although once inside there is no need to maintain this requirments. 
        You must donate almost as much as you receive.
        Participation in clan wars are how you are promoted to elder or co-leader.
        No foul language in any clan chats.
    - question: "What is the clan war strategy?"
      answer: >
        Clan war strategy is not available for strategic purposes.

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information by email.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
